
services:
  swagger_server:
    build: .
    container_name: swagger_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://nak:1234@db:5432/mydatabase
    volumes:
      - .:/usr/src/app
    entrypoint: ["python3"]
    command: ["-m", "swagger_server"]

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nak
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
     image: dpage/pgadmin4
     container_name: pgadmin
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: admin

     ports:
       - "5051:80"
     networks:
       - app_network
     depends_on:
       - postgres

volumes:
  postgres_data:
    driver: local
