services:
  swagger_server:
    build: .
    container_name: swagger_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://nakgeun:12345@db:5432/mydatabase
    volumes:
      - .:/usr/src/app
    entrypoint: ["python3"]
    command: ["-m", "swagger_server"]
    networks:
      - app_network  # app_network 추가

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nakgeun
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  # app_network 추가

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    networks:
      - app_network  # app_network 추가
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge  # app_network 정의
