# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_delivery_method import DataDeliveryMethod  # noqa: F401,E501
from swagger_server.models.data_delivery_mode import DataDeliveryMode  # noqa: F401,E501
from swagger_server.models.dme_type_id import DmeTypeId  # noqa: F401,E501
from swagger_server.models.pull_delivery_details_http import PullDeliveryDetailsHttp  # noqa: F401,E501
from swagger_server.models.push_delivery_details_http import PushDeliveryDetailsHttp  # noqa: F401,E501
from swagger_server.models.streaming_configuration_kafka import StreamingConfigurationKafka  # noqa: F401,E501
from swagger_server.models.uri import Uri  # noqa: F401,E501
from swagger_server import util


class DataOfferInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_delivery_mode: DataDeliveryMode=None, dme_type_id: DmeTypeId=None, production_job_definition: object=None, data_delivery_methods: List[DataDeliveryMethod]=None, data_delivery_schema_ids: List[str]=None, pull_delivery_details_http: PullDeliveryDetailsHttp=None, data_availability_notification_uri: Uri=None, data_offer_termination_notification_uri: Uri=None, push_delivery_details_http: PushDeliveryDetailsHttp=None, streaming_configuration_kafka: StreamingConfigurationKafka=None):  # noqa: E501
        """DataOfferInfo - a model defined in Swagger

        :param data_delivery_mode: The data_delivery_mode of this DataOfferInfo.  # noqa: E501
        :type data_delivery_mode: DataDeliveryMode
        :param dme_type_id: The dme_type_id of this DataOfferInfo.  # noqa: E501
        :type dme_type_id: DmeTypeId
        :param production_job_definition: The production_job_definition of this DataOfferInfo.  # noqa: E501
        :type production_job_definition: object
        :param data_delivery_methods: The data_delivery_methods of this DataOfferInfo.  # noqa: E501
        :type data_delivery_methods: List[DataDeliveryMethod]
        :param data_delivery_schema_ids: The data_delivery_schema_ids of this DataOfferInfo.  # noqa: E501
        :type data_delivery_schema_ids: List[str]
        :param pull_delivery_details_http: The pull_delivery_details_http of this DataOfferInfo.  # noqa: E501
        :type pull_delivery_details_http: PullDeliveryDetailsHttp
        :param data_availability_notification_uri: The data_availability_notification_uri of this DataOfferInfo.  # noqa: E501
        :type data_availability_notification_uri: Uri
        :param data_offer_termination_notification_uri: The data_offer_termination_notification_uri of this DataOfferInfo.  # noqa: E501
        :type data_offer_termination_notification_uri: Uri
        :param push_delivery_details_http: The push_delivery_details_http of this DataOfferInfo.  # noqa: E501
        :type push_delivery_details_http: PushDeliveryDetailsHttp
        :param streaming_configuration_kafka: The streaming_configuration_kafka of this DataOfferInfo.  # noqa: E501
        :type streaming_configuration_kafka: StreamingConfigurationKafka
        """
        self.swagger_types = {
            'data_delivery_mode': DataDeliveryMode,
            'dme_type_id': DmeTypeId,
            'production_job_definition': object,
            'data_delivery_methods': List[DataDeliveryMethod],
            'data_delivery_schema_ids': List[str],
            'pull_delivery_details_http': PullDeliveryDetailsHttp,
            'data_availability_notification_uri': Uri,
            'data_offer_termination_notification_uri': Uri,
            'push_delivery_details_http': PushDeliveryDetailsHttp,
            'streaming_configuration_kafka': StreamingConfigurationKafka
        }

        self.attribute_map = {
            'data_delivery_mode': 'dataDeliveryMode',
            'dme_type_id': 'dmeTypeId',
            'production_job_definition': 'productionJobDefinition',
            'data_delivery_methods': 'dataDeliveryMethods',
            'data_delivery_schema_ids': 'dataDeliverySchemaIds',
            'pull_delivery_details_http': 'pullDeliveryDetailsHttp',
            'data_availability_notification_uri': 'dataAvailabilityNotificationUri',
            'data_offer_termination_notification_uri': 'dataOfferTerminationNotificationUri',
            'push_delivery_details_http': 'pushDeliveryDetailsHttp',
            'streaming_configuration_kafka': 'streamingConfigurationKafka'
        }
        self._data_delivery_mode = data_delivery_mode
        self._dme_type_id = dme_type_id
        self._production_job_definition = production_job_definition
        self._data_delivery_methods = data_delivery_methods
        self._data_delivery_schema_ids = data_delivery_schema_ids
        self._pull_delivery_details_http = pull_delivery_details_http
        self._data_availability_notification_uri = data_availability_notification_uri
        self._data_offer_termination_notification_uri = data_offer_termination_notification_uri
        self._push_delivery_details_http = push_delivery_details_http
        self._streaming_configuration_kafka = streaming_configuration_kafka

    @classmethod
    def from_dict(cls, dikt) -> 'DataOfferInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataOfferInfo of this DataOfferInfo.  # noqa: E501
        :rtype: DataOfferInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_delivery_mode(self) -> DataDeliveryMode:
        """Gets the data_delivery_mode of this DataOfferInfo.


        :return: The data_delivery_mode of this DataOfferInfo.
        :rtype: DataDeliveryMode
        """
        return self._data_delivery_mode

    @data_delivery_mode.setter
    def data_delivery_mode(self, data_delivery_mode: DataDeliveryMode):
        """Sets the data_delivery_mode of this DataOfferInfo.


        :param data_delivery_mode: The data_delivery_mode of this DataOfferInfo.
        :type data_delivery_mode: DataDeliveryMode
        """

        self._data_delivery_mode = data_delivery_mode

    @property
    def dme_type_id(self) -> DmeTypeId:
        """Gets the dme_type_id of this DataOfferInfo.


        :return: The dme_type_id of this DataOfferInfo.
        :rtype: DmeTypeId
        """
        return self._dme_type_id

    @dme_type_id.setter
    def dme_type_id(self, dme_type_id: DmeTypeId):
        """Sets the dme_type_id of this DataOfferInfo.


        :param dme_type_id: The dme_type_id of this DataOfferInfo.
        :type dme_type_id: DmeTypeId
        """

        self._dme_type_id = dme_type_id

    @property
    def production_job_definition(self) -> object:
        """Gets the production_job_definition of this DataOfferInfo.

        Job description based on the DME type specific dataProductionSchema  # noqa: E501

        :return: The production_job_definition of this DataOfferInfo.
        :rtype: object
        """
        return self._production_job_definition

    @production_job_definition.setter
    def production_job_definition(self, production_job_definition: object):
        """Sets the production_job_definition of this DataOfferInfo.

        Job description based on the DME type specific dataProductionSchema  # noqa: E501

        :param production_job_definition: The production_job_definition of this DataOfferInfo.
        :type production_job_definition: object
        """

        self._production_job_definition = production_job_definition

    @property
    def data_delivery_methods(self) -> List[DataDeliveryMethod]:
        """Gets the data_delivery_methods of this DataOfferInfo.


        :return: The data_delivery_methods of this DataOfferInfo.
        :rtype: List[DataDeliveryMethod]
        """
        return self._data_delivery_methods

    @data_delivery_methods.setter
    def data_delivery_methods(self, data_delivery_methods: List[DataDeliveryMethod]):
        """Sets the data_delivery_methods of this DataOfferInfo.


        :param data_delivery_methods: The data_delivery_methods of this DataOfferInfo.
        :type data_delivery_methods: List[DataDeliveryMethod]
        """

        self._data_delivery_methods = data_delivery_methods

    @property
    def data_delivery_schema_ids(self) -> List[str]:
        """Gets the data_delivery_schema_ids of this DataOfferInfo.

        A delivery schema identifier provided by a Data Producer during the data registration procedure  # noqa: E501

        :return: The data_delivery_schema_ids of this DataOfferInfo.
        :rtype: List[str]
        """
        return self._data_delivery_schema_ids

    @data_delivery_schema_ids.setter
    def data_delivery_schema_ids(self, data_delivery_schema_ids: List[str]):
        """Sets the data_delivery_schema_ids of this DataOfferInfo.

        A delivery schema identifier provided by a Data Producer during the data registration procedure  # noqa: E501

        :param data_delivery_schema_ids: The data_delivery_schema_ids of this DataOfferInfo.
        :type data_delivery_schema_ids: List[str]
        """

        self._data_delivery_schema_ids = data_delivery_schema_ids

    @property
    def pull_delivery_details_http(self) -> PullDeliveryDetailsHttp:
        """Gets the pull_delivery_details_http of this DataOfferInfo.


        :return: The pull_delivery_details_http of this DataOfferInfo.
        :rtype: PullDeliveryDetailsHttp
        """
        return self._pull_delivery_details_http

    @pull_delivery_details_http.setter
    def pull_delivery_details_http(self, pull_delivery_details_http: PullDeliveryDetailsHttp):
        """Sets the pull_delivery_details_http of this DataOfferInfo.


        :param pull_delivery_details_http: The pull_delivery_details_http of this DataOfferInfo.
        :type pull_delivery_details_http: PullDeliveryDetailsHttp
        """

        self._pull_delivery_details_http = pull_delivery_details_http

    @property
    def data_availability_notification_uri(self) -> Uri:
        """Gets the data_availability_notification_uri of this DataOfferInfo.


        :return: The data_availability_notification_uri of this DataOfferInfo.
        :rtype: Uri
        """
        return self._data_availability_notification_uri

    @data_availability_notification_uri.setter
    def data_availability_notification_uri(self, data_availability_notification_uri: Uri):
        """Sets the data_availability_notification_uri of this DataOfferInfo.


        :param data_availability_notification_uri: The data_availability_notification_uri of this DataOfferInfo.
        :type data_availability_notification_uri: Uri
        """

        self._data_availability_notification_uri = data_availability_notification_uri

    @property
    def data_offer_termination_notification_uri(self) -> Uri:
        """Gets the data_offer_termination_notification_uri of this DataOfferInfo.


        :return: The data_offer_termination_notification_uri of this DataOfferInfo.
        :rtype: Uri
        """
        return self._data_offer_termination_notification_uri

    @data_offer_termination_notification_uri.setter
    def data_offer_termination_notification_uri(self, data_offer_termination_notification_uri: Uri):
        """Sets the data_offer_termination_notification_uri of this DataOfferInfo.


        :param data_offer_termination_notification_uri: The data_offer_termination_notification_uri of this DataOfferInfo.
        :type data_offer_termination_notification_uri: Uri
        """

        self._data_offer_termination_notification_uri = data_offer_termination_notification_uri

    @property
    def push_delivery_details_http(self) -> PushDeliveryDetailsHttp:
        """Gets the push_delivery_details_http of this DataOfferInfo.


        :return: The push_delivery_details_http of this DataOfferInfo.
        :rtype: PushDeliveryDetailsHttp
        """
        return self._push_delivery_details_http

    @push_delivery_details_http.setter
    def push_delivery_details_http(self, push_delivery_details_http: PushDeliveryDetailsHttp):
        """Sets the push_delivery_details_http of this DataOfferInfo.


        :param push_delivery_details_http: The push_delivery_details_http of this DataOfferInfo.
        :type push_delivery_details_http: PushDeliveryDetailsHttp
        """

        self._push_delivery_details_http = push_delivery_details_http

    @property
    def streaming_configuration_kafka(self) -> StreamingConfigurationKafka:
        """Gets the streaming_configuration_kafka of this DataOfferInfo.


        :return: The streaming_configuration_kafka of this DataOfferInfo.
        :rtype: StreamingConfigurationKafka
        """
        return self._streaming_configuration_kafka

    @streaming_configuration_kafka.setter
    def streaming_configuration_kafka(self, streaming_configuration_kafka: StreamingConfigurationKafka):
        """Sets the streaming_configuration_kafka of this DataOfferInfo.


        :param streaming_configuration_kafka: The streaming_configuration_kafka of this DataOfferInfo.
        :type streaming_configuration_kafka: StreamingConfigurationKafka
        """

        self._streaming_configuration_kafka = streaming_configuration_kafka
