# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataOfferTerminationNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_offer_id: str=None):  # noqa: E501
        """DataOfferTerminationNotification - a model defined in Swagger

        :param data_offer_id: The data_offer_id of this DataOfferTerminationNotification.  # noqa: E501
        :type data_offer_id: str
        """
        self.swagger_types = {
            'data_offer_id': str
        }

        self.attribute_map = {
            'data_offer_id': 'dataOfferId'
        }
        self._data_offer_id = data_offer_id

    @classmethod
    def from_dict(cls, dikt) -> 'DataOfferTerminationNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataOfferTerminationNotification of this DataOfferTerminationNotification.  # noqa: E501
        :rtype: DataOfferTerminationNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_offer_id(self) -> str:
        """Gets the data_offer_id of this DataOfferTerminationNotification.

        Identifies the deleted data offer  # noqa: E501

        :return: The data_offer_id of this DataOfferTerminationNotification.
        :rtype: str
        """
        return self._data_offer_id

    @data_offer_id.setter
    def data_offer_id(self, data_offer_id: str):
        """Sets the data_offer_id of this DataOfferTerminationNotification.

        Identifies the deleted data offer  # noqa: E501

        :param data_offer_id: The data_offer_id of this DataOfferTerminationNotification.
        :type data_offer_id: str
        """
        if data_offer_id is None:
            raise ValueError("Invalid value for `data_offer_id`, must not be `None`")  # noqa: E501

        self._data_offer_id = data_offer_id
