# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pull_delivery_details_http import PullDeliveryDetailsHttp  # noqa: F401,E501
from swagger_server import util


class DataAvailabilityNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_job_id: str=None, pull_delivery_details_http: PullDeliveryDetailsHttp=None):  # noqa: E501
        """DataAvailabilityNotification - a model defined in Swagger

        :param data_job_id: The data_job_id of this DataAvailabilityNotification.  # noqa: E501
        :type data_job_id: str
        :param pull_delivery_details_http: The pull_delivery_details_http of this DataAvailabilityNotification.  # noqa: E501
        :type pull_delivery_details_http: PullDeliveryDetailsHttp
        """
        self.swagger_types = {
            'data_job_id': str,
            'pull_delivery_details_http': PullDeliveryDetailsHttp
        }

        self.attribute_map = {
            'data_job_id': 'dataJobId',
            'pull_delivery_details_http': 'pullDeliveryDetailsHttp'
        }
        self._data_job_id = data_job_id
        self._pull_delivery_details_http = pull_delivery_details_http

    @classmethod
    def from_dict(cls, dikt) -> 'DataAvailabilityNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataAvailabilityNotification of this DataAvailabilityNotification.  # noqa: E501
        :rtype: DataAvailabilityNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_job_id(self) -> str:
        """Gets the data_job_id of this DataAvailabilityNotification.

        data job identifier  # noqa: E501

        :return: The data_job_id of this DataAvailabilityNotification.
        :rtype: str
        """
        return self._data_job_id

    @data_job_id.setter
    def data_job_id(self, data_job_id: str):
        """Sets the data_job_id of this DataAvailabilityNotification.

        data job identifier  # noqa: E501

        :param data_job_id: The data_job_id of this DataAvailabilityNotification.
        :type data_job_id: str
        """

        self._data_job_id = data_job_id

    @property
    def pull_delivery_details_http(self) -> PullDeliveryDetailsHttp:
        """Gets the pull_delivery_details_http of this DataAvailabilityNotification.


        :return: The pull_delivery_details_http of this DataAvailabilityNotification.
        :rtype: PullDeliveryDetailsHttp
        """
        return self._pull_delivery_details_http

    @pull_delivery_details_http.setter
    def pull_delivery_details_http(self, pull_delivery_details_http: PullDeliveryDetailsHttp):
        """Sets the pull_delivery_details_http of this DataAvailabilityNotification.


        :param pull_delivery_details_http: The pull_delivery_details_http of this DataAvailabilityNotification.
        :type pull_delivery_details_http: PullDeliveryDetailsHttp
        """

        self._pull_delivery_details_http = pull_delivery_details_http
