# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataAvailabilityNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_uri: str=None):  # noqa: E501
        """DataAvailabilityNotification - a model defined in Swagger

        :param notification_uri: The notification_uri of this DataAvailabilityNotification.  # noqa: E501
        :type notification_uri: str
        """
        self.swagger_types = {
            'notification_uri': str
        }

        self.attribute_map = {
            'notification_uri': 'notificationUri'
        }
        self._notification_uri = notification_uri

    @classmethod
    def from_dict(cls, dikt) -> 'DataAvailabilityNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataAvailabilityNotification of this DataAvailabilityNotification.  # noqa: E501
        :rtype: DataAvailabilityNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_uri(self) -> str:
        """Gets the notification_uri of this DataAvailabilityNotification.

        The URI where the notification can be delivered  # noqa: E501

        :return: The notification_uri of this DataAvailabilityNotification.
        :rtype: str
        """
        return self._notification_uri

    @notification_uri.setter
    def notification_uri(self, notification_uri: str):
        """Sets the notification_uri of this DataAvailabilityNotification.

        The URI where the notification can be delivered  # noqa: E501

        :param notification_uri: The notification_uri of this DataAvailabilityNotification.
        :type notification_uri: str
        """

        self._notification_uri = notification_uri
