# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.fqdn import Fqdn  # noqa: F401,E501
from swagger_server.models.ipv4_addr import Ipv4Addr  # noqa: F401,E501
from swagger_server.models.ipv6_addr import Ipv6Addr  # noqa: F401,E501
from swagger_server.models.o_auth_grant_type import OAuthGrantType  # noqa: F401,E501
from swagger_server.models.port import Port  # noqa: F401,E501
from swagger_server.models.security_method import SecurityMethod  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class InterfaceDescription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ipv4_addr: Ipv4Addr=None, ipv6_addr: Ipv6Addr=None, fqdn: Fqdn=None, port: Port=None, api_prefix: str=None, security_methods: List[SecurityMethod]=None, grant_types: List[OAuthGrantType]=None):  # noqa: E501
        """InterfaceDescription - a model defined in Swagger

        :param ipv4_addr: The ipv4_addr of this InterfaceDescription.  # noqa: E501
        :type ipv4_addr: Ipv4Addr
        :param ipv6_addr: The ipv6_addr of this InterfaceDescription.  # noqa: E501
        :type ipv6_addr: Ipv6Addr
        :param fqdn: The fqdn of this InterfaceDescription.  # noqa: E501
        :type fqdn: Fqdn
        :param port: The port of this InterfaceDescription.  # noqa: E501
        :type port: Port
        :param api_prefix: The api_prefix of this InterfaceDescription.  # noqa: E501
        :type api_prefix: str
        :param security_methods: The security_methods of this InterfaceDescription.  # noqa: E501
        :type security_methods: List[SecurityMethod]
        :param grant_types: The grant_types of this InterfaceDescription.  # noqa: E501
        :type grant_types: List[OAuthGrantType]
        """
        self.swagger_types = {
            'ipv4_addr': Ipv4Addr,
            'ipv6_addr': Ipv6Addr,
            'fqdn': Fqdn,
            'port': Port,
            'api_prefix': str,
            'security_methods': List[SecurityMethod],
            'grant_types': List[OAuthGrantType]
        }

        self.attribute_map = {
            'ipv4_addr': 'ipv4Addr',
            'ipv6_addr': 'ipv6Addr',
            'fqdn': 'fqdn',
            'port': 'port',
            'api_prefix': 'apiPrefix',
            'security_methods': 'securityMethods',
            'grant_types': 'grantTypes'
        }
        self._ipv4_addr = ipv4_addr
        self._ipv6_addr = ipv6_addr
        self._fqdn = fqdn
        self._port = port
        self._api_prefix = api_prefix
        self._security_methods = security_methods
        self._grant_types = grant_types

    @classmethod
    def from_dict(cls, dikt) -> 'InterfaceDescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfaceDescription of this InterfaceDescription.  # noqa: E501
        :rtype: InterfaceDescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ipv4_addr(self) -> Ipv4Addr:
        """Gets the ipv4_addr of this InterfaceDescription.


        :return: The ipv4_addr of this InterfaceDescription.
        :rtype: Ipv4Addr
        """
        return self._ipv4_addr

    @ipv4_addr.setter
    def ipv4_addr(self, ipv4_addr: Ipv4Addr):
        """Sets the ipv4_addr of this InterfaceDescription.


        :param ipv4_addr: The ipv4_addr of this InterfaceDescription.
        :type ipv4_addr: Ipv4Addr
        """

        self._ipv4_addr = ipv4_addr

    @property
    def ipv6_addr(self) -> Ipv6Addr:
        """Gets the ipv6_addr of this InterfaceDescription.


        :return: The ipv6_addr of this InterfaceDescription.
        :rtype: Ipv6Addr
        """
        return self._ipv6_addr

    @ipv6_addr.setter
    def ipv6_addr(self, ipv6_addr: Ipv6Addr):
        """Sets the ipv6_addr of this InterfaceDescription.


        :param ipv6_addr: The ipv6_addr of this InterfaceDescription.
        :type ipv6_addr: Ipv6Addr
        """

        self._ipv6_addr = ipv6_addr

    @property
    def fqdn(self) -> Fqdn:
        """Gets the fqdn of this InterfaceDescription.


        :return: The fqdn of this InterfaceDescription.
        :rtype: Fqdn
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn: Fqdn):
        """Sets the fqdn of this InterfaceDescription.


        :param fqdn: The fqdn of this InterfaceDescription.
        :type fqdn: Fqdn
        """

        self._fqdn = fqdn

    @property
    def port(self) -> Port:
        """Gets the port of this InterfaceDescription.


        :return: The port of this InterfaceDescription.
        :rtype: Port
        """
        return self._port

    @port.setter
    def port(self, port: Port):
        """Sets the port of this InterfaceDescription.


        :param port: The port of this InterfaceDescription.
        :type port: Port
        """

        self._port = port

    @property
    def api_prefix(self) -> str:
        """Gets the api_prefix of this InterfaceDescription.

        A string representing a sequence of path segments that starts with the slash character.   # noqa: E501

        :return: The api_prefix of this InterfaceDescription.
        :rtype: str
        """
        return self._api_prefix

    @api_prefix.setter
    def api_prefix(self, api_prefix: str):
        """Sets the api_prefix of this InterfaceDescription.

        A string representing a sequence of path segments that starts with the slash character.   # noqa: E501

        :param api_prefix: The api_prefix of this InterfaceDescription.
        :type api_prefix: str
        """

        self._api_prefix = api_prefix

    @property
    def security_methods(self) -> List[SecurityMethod]:
        """Gets the security_methods of this InterfaceDescription.

        Security methods supported by the interface, it takes precedence over the security methods provided in AefProfile, for this specific interface.   # noqa: E501

        :return: The security_methods of this InterfaceDescription.
        :rtype: List[SecurityMethod]
        """
        return self._security_methods

    @security_methods.setter
    def security_methods(self, security_methods: List[SecurityMethod]):
        """Sets the security_methods of this InterfaceDescription.

        Security methods supported by the interface, it takes precedence over the security methods provided in AefProfile, for this specific interface.   # noqa: E501

        :param security_methods: The security_methods of this InterfaceDescription.
        :type security_methods: List[SecurityMethod]
        """

        self._security_methods = security_methods

    @property
    def grant_types(self) -> List[OAuthGrantType]:
        """Gets the grant_types of this InterfaceDescription.


        :return: The grant_types of this InterfaceDescription.
        :rtype: List[OAuthGrantType]
        """
        return self._grant_types

    @grant_types.setter
    def grant_types(self, grant_types: List[OAuthGrantType]):
        """Sets the grant_types of this InterfaceDescription.


        :param grant_types: The grant_types of this InterfaceDescription.
        :type grant_types: List[OAuthGrantType]
        """

        self._grant_types = grant_types
