# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.uri import Uri  # noqa: F401,E501
from swagger_server import util


class PullDeliveryDetailsHttp(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_pull_uri: Uri=None):  # noqa: E501
        """PullDeliveryDetailsHttp - a model defined in Swagger

        :param data_pull_uri: The data_pull_uri of this PullDeliveryDetailsHttp.  # noqa: E501
        :type data_pull_uri: Uri
        """
        self.swagger_types = {
            'data_pull_uri': Uri
        }

        self.attribute_map = {
            'data_pull_uri': 'dataPullUri'
        }
        self._data_pull_uri = data_pull_uri

    @classmethod
    def from_dict(cls, dikt) -> 'PullDeliveryDetailsHttp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PullDeliveryDetailsHttp of this PullDeliveryDetailsHttp.  # noqa: E501
        :rtype: PullDeliveryDetailsHttp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_pull_uri(self) -> Uri:
        """Gets the data_pull_uri of this PullDeliveryDetailsHttp.


        :return: The data_pull_uri of this PullDeliveryDetailsHttp.
        :rtype: Uri
        """
        return self._data_pull_uri

    @data_pull_uri.setter
    def data_pull_uri(self, data_pull_uri: Uri):
        """Sets the data_pull_uri of this PullDeliveryDetailsHttp.


        :param data_pull_uri: The data_pull_uri of this PullDeliveryDetailsHttp.
        :type data_pull_uri: Uri
        """
        if data_pull_uri is None:
            raise ValueError("Invalid value for `data_pull_uri`, must not be `None`")  # noqa: E501

        self._data_pull_uri = data_pull_uri
