# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.uri import Uri  # noqa: F401,E501
from swagger_server import util


class PushDeliveryDetailsHttp(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_push_uri: Uri=None):  # noqa: E501
        """PushDeliveryDetailsHttp - a model defined in Swagger

        :param data_push_uri: The data_push_uri of this PushDeliveryDetailsHttp.  # noqa: E501
        :type data_push_uri: Uri
        """
        self.swagger_types = {
            'data_push_uri': Uri
        }

        self.attribute_map = {
            'data_push_uri': 'dataPushUri'
        }
        self._data_push_uri = data_push_uri

    @classmethod
    def from_dict(cls, dikt) -> 'PushDeliveryDetailsHttp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PushDeliveryDetailsHttp of this PushDeliveryDetailsHttp.  # noqa: E501
        :rtype: PushDeliveryDetailsHttp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_push_uri(self) -> Uri:
        """Gets the data_push_uri of this PushDeliveryDetailsHttp.


        :return: The data_push_uri of this PushDeliveryDetailsHttp.
        :rtype: Uri
        """
        return self._data_push_uri

    @data_push_uri.setter
    def data_push_uri(self, data_push_uri: Uri):
        """Sets the data_push_uri of this PushDeliveryDetailsHttp.


        :param data_push_uri: The data_push_uri of this PushDeliveryDetailsHttp.
        :type data_push_uri: Uri
        """
        if data_push_uri is None:
            raise ValueError("Invalid value for `data_push_uri`, must not be `None`")  # noqa: E501

        self._data_push_uri = data_push_uri
