# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server_reg.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server_reg import util


class DmeTypeIdStruct(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, namespace: str=None, name: str=None, version: str=None):  # noqa: E501
        """DmeTypeIdStruct - a model defined in Swagger

        :param namespace: The namespace of this DmeTypeIdStruct.  # noqa: E501
        :type namespace: str
        :param name: The name of this DmeTypeIdStruct.  # noqa: E501
        :type name: str
        :param version: The version of this DmeTypeIdStruct.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'namespace': str,
            'name': str,
            'version': str
        }

        self.attribute_map = {
            'namespace': 'namespace',
            'name': 'name',
            'version': 'version'
        }
        self._namespace = namespace
        self._name = name
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'DmeTypeIdStruct':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DmeTypeIdStruct of this DmeTypeIdStruct.  # noqa: E501
        :rtype: DmeTypeIdStruct
        """
        return util.deserialize_model(dikt, cls)

    @property
    def namespace(self) -> str:
        """Gets the namespace of this DmeTypeIdStruct.

        Indicating the entity responsible for the DME type definition.  # noqa: E501

        :return: The namespace of this DmeTypeIdStruct.
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace: str):
        """Sets the namespace of this DmeTypeIdStruct.

        Indicating the entity responsible for the DME type definition.  # noqa: E501

        :param namespace: The namespace of this DmeTypeIdStruct.
        :type namespace: str
        """

        self._namespace = namespace

    @property
    def name(self) -> str:
        """Gets the name of this DmeTypeIdStruct.

        Name of the DME type. The string can be any character except “:“ (colon)  # noqa: E501

        :return: The name of this DmeTypeIdStruct.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DmeTypeIdStruct.

        Name of the DME type. The string can be any character except “:“ (colon)  # noqa: E501

        :param name: The name of this DmeTypeIdStruct.
        :type name: str
        """

        self._name = name

    @property
    def version(self) -> str:
        """Gets the version of this DmeTypeIdStruct.

        Version of the DME type. The versioning and allowed characters are according to SemVer [11]  # noqa: E501

        :return: The version of this DmeTypeIdStruct.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this DmeTypeIdStruct.

        Version of the DME type. The versioning and allowed characters are according to SemVer [11]  # noqa: E501

        :param version: The version of this DmeTypeIdStruct.
        :type version: str
        """

        self._version = version
